language: python
cache: pip
install:
- pip install flake8
script:
- make lint
notifications:
  email: false
  slack:
    secure: jbrRb54Epda/ra3j7B10zoOxl5sVxWQbyJtPVVuJ+mISDQJyt4FpJSl13ErtKrza5F++UAMs51qRwgicxTF7yN9mX/8RCDeCI+F4FmOWDTL7lPVCMlNyTAwE/UXL8XsAdoMN47gIkrYyUjnziwD//A+ZQ7pbTbMAzPBRyzH2tB5Ehp9eaU92T1oOGmh8j/rxBJuuQW3sfPb76IqR7F17vU5biDBN/FgWzTrWzS0J5VdbnvIfX+bMF+4VA/WRrCLg2GJyIuGeQtuKF4gBblsQVpu5ax8NnkM+ylWGrAgzzImJfhR+rt+VeZCImBvYiE8836mslqiu8lhQxQ96PbF8xdMy/qeKujPrHV6ilr5j3O2iVihd2vq48rAVwMoYtJL9+5I7g5G6lnlLLKhEahgTbT3GRc5r5bno8PhkqqQ3+YFyKbNeIqeH8SVF3sI740COK5MJ8/PHO9rc9kVhKrZ3n4Y6rPb7d92gW9XFcjKBukuJ7N0IeV+kSRvVZXJtN58bUkg4ZycEQ1jUUys4hMxh1opRn3IBBk4ZYyEMrswIdAjire3hE6Iq9aalSPDi0byg+skjT54VZgUMj/bFfUPzsLWr1PMXXmvCb4eskq9EoJVc43YrwaykMTx4phmqx+e2uBhd0LufFd8Kg2AfoyPMZplTpkV85uTvBy/5eCx1sG4=
    rooms:
      secure: mV0iQ24H1GGfIe1VP51Cw3YJHhFf62wQLjRz8iEEDniltmXb9PBUjeERyAbbEWcWZ+H/EIQ3JZl6ZEcX5NngkTLPZAPclejwZrvizMpE3d5ep4QspnsupYb+wbMpjwAcXlL3kTZuGmOMkmuNZTuEsOEXPSw+HUkNTA+f5ASJmO/p8asv7dfpu5E6wQXisd3B9K8ViHlRP41dEddV4nEYZN8WyY8PXuVl1FTOCkiW6wRxLGV8GaaN0YAWVnTl2DK2Mk7BUc/4jkgK7URzSKYu5WSIvHgV55ZF5GlCBpieto90na9DK4ccjYeVZFOflUdzniSGHr9inoOyysBe0+rG0U8+sgDXRV2loZFua309RBqpdXjC/Bf2fHinX+PlgFkEE7BfaYuS7vNdfFo7xp77d3QYMVJ2hVMJn854rrF9OeuHqlSyTxQppY7kez+6oEumfZb5VMf9ij5bLFqt1eWQaUPE4UOh93BGmVkJeNehGnHY3GlGoPS9bIgpFWzYcXp0rwE5+M0s4yyGLXwq4/aFEbUb+LXufgGEPl4HNq6r4FmjJgRlTV/Ge2+y43NQbibno8gxQo/f1b8sp5Lin17E1pfNlgY8Zxjr+KAsEGtoJlvyh2AAaH8SQipPB7b8vpH7EBt3seNcw0HI52qCrNMDENDn/JIWlrXjacWvl3vhD3Q=
