language: python
cache: pip
install:
- pip install flake8
script:
- make lint
notifications:
  email: false
  slack:
    rooms:
      secure: mV0iQ24H1GGfIe1VP51Cw3YJHhFf62wQLjRz8iEEDniltmXb9PBUjeERyAbbEWcWZ+H/EIQ3JZl6ZEcX5NngkTLPZAPclejwZrvizMpE3d5ep4QspnsupYb+wbMpjwAcXlL3kTZuGmOMkmuNZTuEsOEXPSw+HUkNTA+f5ASJmO/p8asv7dfpu5E6wQXisd3B9K8ViHlRP41dEddV4nEYZN8WyY8PXuVl1FTOCkiW6wRxLGV8GaaN0YAWVnTl2DK2Mk7BUc/4jkgK7URzSKYu5WSIvHgV55ZF5GlCBpieto90na9DK4ccjYeVZFOflUdzniSGHr9inoOyysBe0+rG0U8+sgDXRV2loZFua309RBqpdXjC/Bf2fHinX+PlgFkEE7BfaYuS7vNdfFo7xp77d3QYMVJ2hVMJn854rrF9OeuHqlSyTxQppY7kez+6oEumfZb5VMf9ij5bLFqt1eWQaUPE4UOh93BGmVkJeNehGnHY3GlGoPS9bIgpFWzYcXp0rwE5+M0s4yyGLXwq4/aFEbUb+LXufgGEPl4HNq6r4FmjJgRlTV/Ge2+y43NQbibno8gxQo/f1b8sp5Lin17E1pfNlgY8Zxjr+KAsEGtoJlvyh2AAaH8SQipPB7b8vpH7EBt3seNcw0HI52qCrNMDENDn/JIWlrXjacWvl3vhD3Q=
